services:
  - type: web
    name: lash-bot-backend
    env: python
    runtime: python3.12
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_USERNAME
        sync: false
