services:
  - type: web
    name: lashes-booking-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
        value: 8646567713:AAGaYReANb-Ua4NSoHIOlk06GKKExL-DS6M
      - key: ADMIN_ID
        value: 1834686956
      - key: ADMIN_SECRET_KEY
        value: default-secret
      - key: DATABASE_URL
        value: postgresql://postgres:LE315K4b80hrPd0f@db.yhfrygwnvtyutsakouoq.supabase.co:5432/postgres
      - key: WEBHOOK_URL
        value: https://liquid-glass-calendar-design.onrender.com/webhook
      - key: MINI_APP_URL
        value: https://liquid-glass-calendar-design.netlify.app
      - key: BOT_USERNAME
        value: YourLashess_bot
    healthCheckPath: /health
